name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"

  build-mac-x64-arm64:
    runs-on: macos-11
    needs: set-date

    steps:
      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Publish [osx]
        run: |
          dotnet publish BBDown -r osx-x64 -c Release -o artifact
          dotnet publish BBDown -r osx-arm64 -c Release -o artifact-arm64

      - name: Package [osx]
        run: |
          cd artifact
          zip ../BBDown_${{ needs.set-date.outputs.date }}_osx-x64.zip BBDown
          cd ../artifact-arm64
          zip ../BBDown_${{ needs.set-date.outputs.date }}_osx-arm64.zip BBDown

      - name: Upload Artifact [osx-x64]
        uses: actions/upload-artifact@v4
        with:
          name: BBDown_osx-x64
          path: BBDown_${{ needs.set-date.outputs.date }}_osx-x64.zip

      - name: Upload Artifact [osx-arm64]
        uses: actions/upload-artifact@v4
        with:
          name: BBDown_osx-arm64
          path: BBDown_${{ needs.set-date.outputs.date }}_osx-arm64.zip
